/**
* Swagger Petstore
* This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
*
* The version of the OpenAPI document: 1.0.0
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package io.hexaforce.models

import org.ktorm.dsl.*
import org.ktorm.schema.*
import org.ktorm.database.Database
import .*


/**
 * 
 * @param id 
 * @param name 
 */
object Categorys : BaseTable<Category>("Category") {
    val id = long("id") /* null */
    val name = text("name") /* null */

    /**
     * Create an entity of type Category from the model
     */
    override fun doCreateEntity(row: QueryRowSet, withReferences: Boolean) = Category(
        id = row[id]  /* kotlin.Long? */,
        name = row[name]  /* kotlin.String? */
    )

    /**
    * Assign all the columns from the entity of type Category to the DML expression.
    *
    * Usage:
    *
    * ```kotlin
    * let entity = Category()
    * database.update(Categorys, {
    *     assignFrom(entity)
    * })
    * ```
    * @return the builder with the columns for the update or insert.
    */
    fun AssignmentsBuilder.assignFrom(entity: Category) {
        this.apply {
            set(Categorys.id, entity.id)
            set(Categorys.name, entity.name)
        }
    }

}


